### ISSUE TITLE
Segmentation fault - invalid memory reference

### ISSUE THREAD

**Issue by 13015339981** [UCLA-Plasma-Simulation-Group/QuickPIC-OpenSource#39]
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

$  mpirun -np 1 ./qpic.e

Backtrace for this error:
#0  0x2b82fff575ef in ???
#1  0x2b83002bf9f6 in ???
#2  0x2b82fe40d4c5 in __json_file_module_MOD_json_file_check_for_errors
	at /tmp/rpm/spack-stage-json-fortran-6.11.0-x6yn2yap3hwd4yfjtfwdo7jdb33w5ysa/spack-src/src/json_file_module.F90:330
#3  0x499c03 in ???
#4  0x4b19e5 in ???
#5  0x404275 in ???
#6  0x2b8300186504 in ???
#7  0x4042d1 in ???
#8  0xffffffffffffffff in ???
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 312737 on node cas338 exited on signal 11 (Segmentation fault).

**Comment by 13015339981** [comment]
Please tell me how to solve this problem, this is my input file. Thanks.
[qpinput.txt](https://github.com/UCLA-Plasma-Simulation-Group/QuickPIC-OpenSource/files/6860956/qpinput.txt)

**Comment by lifei07** [comment]
Hello,

The probable reason for this segfault would be the version of the json-fortran library. I noticed you used 6.11.0 with which the code might not be compatible. I suggest using an earlier version like 6.3.0.

Fei
